#!/usr/bin/env bash

#  Copyright (C) 2019-2021 Maker Ecosystem Growth Holdings, INC.

#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

# shellcheck source=lib/common.sh
. "$LIB_DIR/common.sh"

# export SETH_ASYNC=yes

# dappCreate now returns the contract *address* directly, not a tx hash.
# If any deployment fails, abort this script.
VAT_FAB="$(dappCreate dss-deploy-1_2 VatFab)" || exit 1
JUG_FAB="$(dappCreate dss-deploy-1_2 JugFab)" || exit 1
VOW_FAB="$(dappCreate dss-deploy-1_2 VowFab)" || exit 1
CAT_FAB="$(dappCreate dss-deploy-1_2 CatFab)" || exit 1
DOG_FAB="$(dappCreate dss-deploy     DogFab)" || exit 1
DAI_FAB="$(dappCreate dss-deploy-1_2 DaiFab)" || exit 1
MCD_JOIN_DAI_FAB="$(dappCreate dss-deploy-1_2 DaiJoinFab)" || exit 1
FLAP_FAB="$(dappCreate dss-deploy-1_2 FlapFab)" || exit 1
FLOP_FAB="$(dappCreate dss-deploy-1_2 FlopFab)" || exit 1
FLIP_FAB="$(dappCreate dss-deploy-1_2 FlipFab)" || exit 1
CLIP_FAB="$(dappCreate dss-deploy     ClipFab)" || exit 1
CALC_FAB="$(dappCreate dss-deploy     CalcFab)" || exit 1
SPOT_FAB="$(dappCreate dss-deploy-1_2 SpotFab)" || exit 1
POT_FAB="$(dappCreate dss-deploy-1_2 PotFab)" || exit 1
CURE_FAB="$(dappCreate dss-deploy     CureFab)" || exit 1
END_FAB="$(dappCreate dss-deploy      EndFab)" || exit 1
ESM_FAB="$(dappCreate dss-deploy      ESMFab)" || exit 1
PAUSE_FAB="$(dappCreate dss-deploy-1_2 PauseFab)" || exit 1

# export SETH_ASYNC=no

logAddr "VAT_FAB" "$VAT_FAB"
logAddr "JUG_FAB" "$JUG_FAB"
logAddr "VOW_FAB" "$VOW_FAB"
logAddr "CAT_FAB" "$CAT_FAB"
logAddr "DOG_FAB" "$DOG_FAB"
logAddr "DAI_FAB" "$DAI_FAB"
logAddr "MCD_JOIN_DAI_FAB" "$MCD_JOIN_DAI_FAB"
logAddr "FLAP_FAB" "$FLAP_FAB"
logAddr "FLOP_FAB" "$FLOP_FAB"
logAddr "FLIP_FAB" "$FLIP_FAB"
logAddr "CLIP_FAB" "$CLIP_FAB"
logAddr "CALC_FAB" "$CALC_FAB"
logAddr "SPOT_FAB" "$SPOT_FAB"
logAddr "POT_FAB" "$POT_FAB"
logAddr "CURE_FAB" "$CURE_FAB"
logAddr "END_FAB" "$END_FAB"
logAddr "ESM_FAB" "$ESM_FAB"
logAddr "PAUSE_FAB" "$PAUSE_FAB"

cat > "$OUT_DIR/load-fabs-addr-temp" <<EOF
#!/bin/bash
export VAT_FAB=$VAT_FAB
export JUG_FAB=$JUG_FAB
export VOW_FAB=$VOW_FAB
export CAT_FAB=$CAT_FAB
export DOG_FAB=$DOG_FAB
export DAI_FAB=$DAI_FAB
export MCD_JOIN_DAI_FAB=$MCD_JOIN_DAI_FAB
export FLAP_FAB=$FLAP_FAB
export FLOP_FAB=$FLOP_FAB
export FLIP_FAB=$FLIP_FAB
export CLIP_FAB=$CLIP_FAB
export CALC_FAB=$CALC_FAB
export SPOT_FAB=$SPOT_FAB
export POT_FAB=$POT_FAB
export CURE_FAB=$CURE_FAB
export END_FAB=$END_FAB
export ESM_FAB=$ESM_FAB
export PAUSE_FAB=$PAUSE_FAB
EOF
